#!/bin/awk -f
BEGIN {
    valid=0
}
{
    # Here we store the number of occurences in a given string
    tempValid = 0;

    # process the input
    needle=substr($2, 0, 1);
    pos1=substr($1, 0, index($1,"-")-1) + 0
    pos2=substr($1, index($1,"-")+1, length($1)) + 0
    haystack=$3

    # Iterate over the part of the
    # string between first and second possible occurences
    idx=pos1
    while(idx <= pos2) {
        # If we have an occurence, in one of the positions, count that in
        if ((idx == pos1 || idx == pos2) && substr(haystack, idx, 1) == needle) {
            tempValid++
        }
        # increase the counter
        idx++
    }

    # There should be only one occurence
    if (tempValid == 1 ) {
        valid++;
    }
}
END {
    print "Valid passwords: ", valid
}
